PRINT 'CREATING TABLES '
GO

IF OBJECT_ID('EMPLOYEE') IS NOT NULL
   DROP TABLE DBO.EMPLOYEE
GO
CREATE TABLE DBO.EMPLOYEE
(
EMPLOYEEID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
FIRSTNAME  VARCHAR(50),
LASTNAME   VARCHAR(50)
)
GO

IF OBJECT_ID('TIMECARD') IS NOT NULL
   DROP TABLE DBO.TIMECARD
GO
CREATE TABLE DBO.TIMECARD
(
TIMECARDID  INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
EMPLOYEEID  INT NOT NULL,
HOURSWORKED TINYINT NOT NULL,
HOURLYRATE  MONEY NOT NULL,
DATEWORKED  DATETIME NOT NULL
)
GO

DECLARE @TOTAL_TABLES INT
SET @TOTAL_TABLES = 2