[a]
a=2
a=2
[b]
b=3
b=3




[c]
c=4
c=4


===ddd===
; ddd
===ddd===

[Rainmeter]
Update=5000
AccurateText=1
DynamicWindowSize=1



---Measures---



[MeasureParent1]
Measure=WebParser
URL=https://google.com
RegExp=(?siU)^(.{30}).*$
OnUpdateAction=[!UpdateMeasure MeasureChild1][!UpdateMeter *][!Redraw]
DynamicVariables=1

[MeasureChild1]
Measure=WebParser
URL=[MeasureParent1]
StringIndex=1
DynamicVariables=1

[MeasureParent2]
Measure=Plugin
Plugin=FileView
Path="C:\Program Files\Rainmeter"
ShowDotDot=0
ShowFolder=0
Count=3
OnUpdateAction=[!UpdateMeasure MeasureChild2][!UpdateMeter *][!Redraw]
DynamicVariables=1

[MeasureChild2]
Measure=Plugin
Plugin=FileView
Path=[MeasureParent2]
Type=FileName
Index=1
DynamicVariables=1

[mFileParse]
Measure=WebParser
URL=File://#CURRENTPATH#[&mTitle]\[&mApp1].txt
UpdateRate=3600
RegExp=(?siU)Debug=(.*)\nCurrent=(.*)\nRegEx=(.*)\n ...etc... etc...
DynamicVariables=1

---Meters---

[Dummy]
Meter=Image
W=100
H=100
SolidColor=255,0,0,255
DynamicVariables=1

