
[Variables]
Alpha=30
Aqua=0,255,255
AquaDark=#Aqua#,150


========================================
; STYLES
========================================
[sGlobalText]
FontFace=Trebuchet MS
StringAlign=CenterCenter
StringStyle=Bold
FontSize=9
FontColor=#White#
AntiAlias=1
ClipString=2
DynamicVariables=1
Group=VLC

[sHighlight]
MouseOverAction=[!SetOption #CURRENTSECTION# FontColor "#Green#"][!UpdateMeter #CURRENTSECTION#][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# FontColor ""][!UpdateMeter #CURRENTSECTION#][!Redraw]

========================================
; PROCESSES
========================================
[mProcess]
Measure=Calc
Formula=1
DynamicVariables=1
; Enable Disable System/Drives Bar:
IfCondition=(mProcess2=1) || (mProcess3=1) || (mProcess4=1)
IfTrueAction=[!DeactivateConfig "Barred\SystemBar" "SystemBar2-0.ini"][!DeactivateConfig "Barred\DisksBar" "DrivesBar1.ini"][!Redraw]
IfFalseAction=[!ActivateConfig "Barred\SystemBar" "SystemBar2-0.ini"][!ActivateConfig "Barred\DisksBar" "DrivesBar1.ini"][!Redraw]
; Foobar:
IfCondition3=mProcess1=1
IfTrueAction3=[!EnableMeasureGroup Foobar][!ShowMeterGroup Foobar][!UpdateMeterGroup Foobar][!Redraw]
IfFalseAction3=[!DisableMeasureGroup Foobar][!HideMeterGroup Foobar][!UpdateMeterGroup Foobar][!Redraw]

[mProcess1]
Measure=Process
ProcessName=foobar2000.exe
[mProcess2]
Measure=Process
ProcessName=PotPlayerMini64.exe
[mProcess3]
Measure=Process
ProcessName=VLC.exe
