finish
/CLEAR,NOSTART

/REPLOT,RESIZE

~PARAIN,'test','x_t','C:\test',SOLID,0,0

!~PARAIN,'test','x_t','C:\test',SOLID,0,0

*CFCLOS

/NOPR
/GO

/prep7
et,1,solid70
mp,kxx,1,204
mp,kxx,2,0.3
/facet,norm
vglue,all
!vovlap,all
vsel,all
vatt,1
vsel,s,,,10
vsel,a,,,9
vatt,2

VPLOT
ALLSEL,ALL

ESIZE,0.003,0,

VSEL,s , , ,9
VSEL,a , , ,10
VSWEEP,all

!*
ESIZE,0.005,0,
VSEL,s , , ,8
VSWEEP,all

!ESIZE,0.002,0,
!MSHAPE,1,3D
!MSHKEY,0
!VSEL,s , , ,12
!VSEL,a , , ,13
!MOPT,PYRA,OFF
!VMESH,all



ESIZE,0.005,0,
MSHAPE,1,3D
MSHKEY,0
VSEL,all
MOPT,PYRA,OFF
VMESH,all

VPLOT
VSEL,S , , ,8
VSEL,a , , ,13

ALLSEL,BELOW,VOLU

DA,all,TEMP,77

VSEL,S, , ,      14
ALLSEL,BELOW,VOLU
DA,all,TEMP,293

FINISH

/SOL
TREF,293,
ALLSEL,ALL
/STATUS,SOLU
SOLVE
FINISH
/POST1
!*
/EFACET,1
PLNSOL, TEMP,, 2












finish
/prep7
etchg,tts

/PREP7
ETCHG,TTS
LSCLEAR,ALL

APLOT
DA,37,UX,
DA,37,UY,

LDREAD,TEMP,,, , ,'test','rth',' '

!-------------------
mp,ex,1,70e9
mp,prxy,1,0.33
mp,alpx,1,2.4e-5
mp,dens,1,2700

mp,ex,2,26e9
mp,prxy,2,0.20
mp,alpx,2,2.5e-5
mp,dens,2,2000

asel,s,loc,z
da,all,symm

acel,0,9.8,0

asel,s,,,25
asel,a,,,36
asel,a,,,23
asel,a,,,38
asel,a,,,22
asel,a,,,21
asel,a,,,37
!asel,a,,,24
sfa,all,1,pres,1e5


asel,s,,,2
asel,a,,,3
asel,a,,,4
asel,a,,,5
asel,a,,,69
asel,a,,,87
sfa,all,1,pres,1e5

FINISH

/SOL
TREF,293,
ALLSEL,ALL
/STATUS,SOLU
SOLVE

/VIEW,1,,,1
/ANG,1
/REP,FAST
FINISH

/POST1
!*
!/DSCALE,ALL,1.0
!/EFACET,1
!PLNSOL, U,SUM, 2,1.0
!*

/DSCALE,ALL,OFF
/EFACET,1
PLNSOL, S,INT, 0,1.0


