package com.mg.groovy.samples.db.infra

import groovy.sql.Sql 
import groovy.text.SimpleTemplateEngine as STE

class DbHelper { 
	Sql db
	
	DbHelper() { 
		//		def source = new org.hsqldb.jdbc.jdbcDataSource() 
		//		source.database = 'jdbc:hsqldb:mem:GIA' 
		//		source.user = 'sa' 
		//		source.password = '' 
		//		db = new Sql(source)
		
		def source = new org.hsqldb.jdbc.jdbcDataSource() 
		source.database = 'jdbc:hsqldb:file:./src/com/mg/groovy/samples/db/testdb' 
		source.user     = 'sa' 
		source.password = '' 
		db = new groovy.sql.Sql(source)
		
		setUp()
		
	}
	
	def simpleTemplate = new STE().createTemplate(''' 
    DROP   INDEX ${lowname}Idx IF EXISTS; 
    DROP   TABLE $name    IF EXISTS; 
    CREATE TABLE $name ( 
        ${lowname}Id    INTEGER GENERATED BY DEFAULT AS IDENTITY, 
    $fields 
    ); 
    CREATE INDEX ${lowname}Idx ON $name (${lowname}Id);''')
	
	def executeDdl(DataAccessObject dao) { 
		def template = simpleTemplate 
		def binding = [ 
				name:    dao.tablename, 
				lowname: dao.tablename.toLowerCase(), 
				fields:  dao.schema.collect{ key, val ->  "    ${key.padRight(12)} $val" }.join(",\n") 
				] 
		def stmt = template.make(binding).toString() 
		db.execute stmt 
	} 
	
	
	
	def setUp() {
		
		println  "dropping table and index..."
		db.execute '''
	        DROP   INDEX musicIdx IF EXISTS;
	        DROP   TABLE musics    IF EXISTS;
	        '''
		
		println "re-criate table and index..."
		db.execute ''' 
	        CREATE TABLE musics ( 
	            id   INTEGER GENERATED BY DEFAULT AS IDENTITY, 
	            artist VARCHAR(64),
	            name   VARCHAR(64), 
	            album    VARCHAR(64), 
	            date_launched DATE 
	        ); 
	        CREATE INDEX musicIdx ON musics (id); 
	        ''' 
		
		println "inserting some records..."
		def sql_insert = "insert into musics(artist, album, name, date_launched) values(?, ?, ?, ?)"
		
		db.execute sql_insert, ['AC/DC', 'Black Ice', '', '2008-12-01']
		db.execute sql_insert, ['Gun N\' Roses', 'Chinise Democracy', '', '2008-12-01']
		
		println "... setup concluded!\n"
	}	
	
	
}