 "Examples for Chapter 33, Managing Source Code.
Copyright © 1996, Alec Sharp

To try the examples, highlight the appropriate code and select either
'do it', 'inspect it', or 'print it' from the operate menu, as appropriate.

This code should NOT be filed in.

------------------------------------------------------------------------------------------------------ "

"Empty the Change Set"
ChangeSet noChanges.

"Tell the browser to remove changes from the Change Set when you file them out"
Browser removeChangesOnFileOut: true.
