 "Examples for Chapter 35, Public Domain Code and Information.
Copyright © 1996, Alec Sharp

To try the examples, highlight the appropriate code and select either
'do it', 'inspect it', or 'print it' from the operate menu, as appropriate.

This code should NOT be filed in.

------------------------------------------------------------------------------------------------------ "

"The following Web addresses were current at the time of writing.
They are included here in case you want to cut and paste them"

UIUC Smalltalk Archive. 			http://st-www.cs.uiuc.edu
Smalltalk FAQ. 					http://xcf.berkeley.edu/pub/misc/smalltalk/FAQ
Smalltalk FAQ (plain text). 		http://xcf.berkeley.edu/pub/misc/smalltalk/FAQ/FAQ.txt
Another Smalltalk FAQ.			http://www.cis.ohio-state.edu/hypertext/faq/usenet/smalltalk-faq/faq.html
Patterns Home Page.			http://st-www.cs.uiuc.edu/users/patterns/patterns.html
Portland Patterns Repository. 	http://c2.com/ppr/titles.html
The Smalltalk Developer's Site	http://www.rwi.com/smalltalk/smalltalk.html
Yahoo Smalltalk page. 			http://www.yahoo.com/Computers/Languages/Smalltalk/
Jeff McAffer's home page		http://www.oti.com/jeffspg/smaltalk.htm

ParcPlace-Digitalk.  				http://www.parcplace.com/
VisualAge.  						http://www.software.ibm.com/software/ad/vastub.html

Runtime Packager				http://www.advbool.com/advbool/
The Smalltalk Store				http://www.smalltalk.com/
Smalltalk Prof. Debug Package	http://www2.pcix.com/~traymond/ 
ENVY							http://www.oti.com
Review of ENVY					http://www.bytesmiths.com/pubs/9209Envy.html

"Note the spelling of the document: smaltalk.htm because of file naming limitations"
Jeff McAffer's home page		http://www.oti.com/jeffspg/smaltalk.htm



"The FTP address for the Smalltalk Archives"

st.cs.uiuc.edu