 "Examples for Chapter 5, Instance Creation.
Copyright © 1996, Alec Sharp

To try the examples, highlight the appropriate code and select either
'do it', 'inspect it', or 'print it' from the operate menu, as appropriate.

This code should NOT be filed in.

------------------------------------------------------------------------------------------------------ "

Array new capacity.
Bag new capacity.
Dictionary new capacity.
Set new capacity.
List new capacity.
OrderedCollection new capacity.

