 "Examples for Chapter 7, Global Variables.
Copyright © 1996, Alec Sharp

To try the examples, highlight the appropriate code and select either
'do it', 'inspect it', or 'print it' from the operate menu, as appropriate.

This code should NOT be filed in.

------------------------------------------------------------------------------------------------------ "

Browser browseAllCallsOn: (MyPoolDictionary associationAt: #Config).

ComposedTextView openSystemWorkspace.

CEnvironment commandLine.
CEnvironment getenv: 'LOGNAME'

Smalltalk version.
ObjectMemory versionId.
ObjectMemory versionId at: 5.
